### ISSUE TITLE
Updating Identity Password

### ISSUE THREAD

**Issue by Petervdburg** [albertony/dcompermex#4]
Hi Albert, my situation is I have a legacy business critical application that have a number of different Windows components that need to have their password rotated by an external trigger. This application has 2x "DCOM Config" objects that also need their Identity Password rotated. 

I've read the Source code (both yours and Microsoft's) that indicates that when running the "dcomperm -runas {12345678-1234-1234-1234-00aa00bbf7c7} redmond\jdoe password" command, it should actually update the password. However, running a precompiled version, it doesnt appear to and after I run the application all indications are that it still has the old password.

My questions are: 

- is the dcomperm command as shown supposed to update the password? Where can I look to confirm a change? If I change the user, I see the change in both registry & dcomcnfg, but no change in the password field (number of dots).
- Both yours and Microsoft's dcomperm.h have a duplicate set of DWORD assignments (sorry if I get the lingo wrong). Could this be an issue?:
DWORD GetRunAsPassword (
    LPTSTR AppID,
    LPTSTR Password
    );

DWORD SetRunAsPassword (
    LPTSTR AppID,
    LPTSTR Principal,
    LPTSTR Password
    );

DWORD GetRunAsPassword (
    LPTSTR AppID,
    LPTSTR Password
    );

DWORD SetRunAsPassword (
    LPTSTR AppID,
    LPTSTR Password
    );

Not being an experienced developer, I'm attempting to get some confidence that I'm on the right track to solving this issue I have before I go down the track of compiling etc.

Thanks

**Comment by albertony** [comment]
Hi.

I assume changing the user works, and that the problem is specifically setting the password? And you get no errors or other indications that something went wrong? Could be worth trying both x86 and x64 versions, although its more of a shot in the dark..

> Both yours and Microsoft's dcomperm.h have a duplicate set of DWORD assignments (sorry if I get the lingo wrong). Could this be an issue?

That is not intentional, but would not cause any issues. Though, I will clean it up. Thanks for pointing it out.

I had a quick look into the code, but could not see any obvious things, so I need to debug it when I get time.

The problem is most probably within this function (which is unchanged from Microsoft's code):

https://github.com/albertony/dcompermex/blob/5716b315aa083614753a99bcb99c11a04a5d71d3/SrvcMgmt.Cpp#L96-L180

**Comment by albertony** [comment]
Spent some more time testing. Could not find any problems, but not sure how realistic my test case is compared to yours..

While testing and debugging, I found some small improvements that could be done, and released it as a v2.0.3. Changes should not affect your issue in any way, but perhaps the feature to retrieve existing runas information (`DComPermEx.exe -runas <appid>`) can be useful in further investigations?

**Comment by Petervdburg** [comment]
Great stuff- thanks so much! I downloaded and tested and it worked as designed. The Retrieve function is very useful and was able to verify the state of the Identity. The password update worked.
